---
pool: 'Default'
trigger:
  - azuredevops
jobs:
  - job: 'spc_sonar'
    steps:
      - task: SonarQubePrepare@5
        inputs:
          SonarQube: 'sonar'
          scannerMode: 'Maven/Gradle'
          projectVersion: '1.0'
          extraProperties: 'sonar.projectKey=tejaswini1811_spc-az'
      - task: Maven@3 
        inputs:
          mavenPOMFile: 'pom.xml'
          goals: 'package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml' 
          javaHomeOption: 'Path'
          jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
          mavenVersionOption: 'Path'
          mavenDirectory: '/opt/apache-maven-3.6.3'
          sonarQubeRunAnalysis: true
          isJacocoCoverageReportXML: true
          sqMavenPluginVersionChoice: 'latest'
      - task: SonarQubePublish@5
        inputs:
          pollingTimeoutSec: '300'



